language: node_js
sudo: required
cache:
  directories:
  - node_modules
matrix:
  include:
  - node_js: stable
    script: xvfb-run -a wct --simpleOutput -l firefox -l chrome
    addons:
      firefox: latest
      apt:
        sources:
        - google-chrome
        packages:
        - google-chrome-stable
  - node_js: node
    script:
    - |
      if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then







        wct --simpleOutput -s 'Windows 10/microsoftedge' -s 'Windows



      8.1/internet explorer@11' -s 'Windows 7/internet explorer@10' -s 'OS X 10.10/safari@8' -s 'OS X 10.9/safari@7'
      fi
before_script:
- npm install -g bower polylint web-component-tester
- bower install
- polylint
env:
  global:
  - secure: qWAnfdCt+M+aNIKs+0iWMn4Fg61SaRelUd79BqwkZeI9Aldwv54yqc+J+p5J+PwRoBNCYfzOxQeI/2SRwzGb8ZytlbY65nacR8iCFwgOkeNJZcKvP5IqcxVSiGg4xXrMzZX7kI0GXGqUCWyUwFZ1XZSonJObnk92ZWf8v1qvYd+eqQprerkdG7ODN53o6JreDhcIxAuaPBdIXkqInBha8Wj0vTXU+K/8PP32wylxWeylUt0VUE9jdZz07BkpUIvZxpQ+VK9TqsHAPV4ymCa02Bcvxal0p6zOTwjmouN2NeLIT1VU4SsHqMkUOu9EvfCEETYH2E6cGzT+vpdnLKC8O2WfxwRy1XNubh2lrTG9IXcb9BBCIGurImhSFxeLTU4P2rg7t48FLmg+9zQlWcKlmkN9jEvkqfAOJIkFMSpggjHu1Cxj9QjIPChCM+LULdsKShQKbd7Gv5iV70tlRRIb78LVdk8qSTOTa19b6wZQy9Gb4sJnfVCfx0eKGg+FubLxgwTn2hhoUdU9cfgX42bZQ59UjLTRQjJwdKOhy5zFevgtdGP1nONXWHDPkpa2M9iQPvRbQ95LCYm40yCerfbhKTJmdnMKwEgtFA/HniWn64ujydiJ0/UMCzn3UYIC75zb+ETKAZCGkHmL3UYkch9V59qCnhtF/5LR91ylAY4NLMQ=
  - secure: k+ZP9HMOxiTEAU0UvM0tAVumzq3Mvpooh3/DGHPb/9hCW/dECAOrenJBDwiDsmuXY2WPppb9Nu8M5Ek/grse5mysm954SCKzFpWAk1m1MDwmcoLjCo6I/S1/BCAHxQbxIynYf0eSr56MpM94+6RxmFTd9SPXKoJmO0X3v5TpDOXl6yGTI8oKa6d6RSGOfaXl8Zaxpz4IG7FZbLaheoeyfzPzB4rg3Bn/klIxBcL/timuce1ckWJSVyCbvbd8Hphouh8yMfKKl3LWWAOkCVGdM4hTQNBZNHTG2Mno7sLpxKEJN9EMLEAFxiCr5vGf690eZQY9YpLt3/zT6pCIaz3ekPNcslgULLSIN13CXeP0Ms6r5DqpEk9MkfmiRpKDmedHOzKwUIQ0cIx79SecsEKSQjSQrOT+DfsmQHpCL06Ou0yz61em5Rt+0xLkGPJpXRkCNiNieavcdCmw+hZCZCxGef7Fq+I/teh3Yws85fLjPLrtOgPQqJRwDwBdxzVflf+mBqCYKqqc2Omg7BQCzcis+A0iGAYpvBqcy9bZnaiq/ynxdmg2w8glGh/KyFCGkIll8op9l/rdmb2XEmSzjzCtgPvasnhJfUBvIsmp+P2Y6f6kbD6mp68h5CzmHDNLqrGVea5vEN1Sp16vOZN4ODCYvW8rxCBIv+x/qEje4MCyTcQ=
dist: trusty
node_js: stable
addons:
  firefox: '46.0'
  sauce_connect: true
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
